### ISSUE TITLE
优化的建议

### ISSUE THREAD

**Issue by cutethotw** [AirportR/FullTclash#1]
1.login.py生成的my_bot.session默认在\libs里，可以生成后移动到根目录减少一次手动操作
2.授权用户列表默认为空，可以将管理员默认添加进去减少一次手动操作
3.md文档目前采取的并列的方式，可以切换为顺序式（1.->2.->3.->……）更方便小白用户理解

**Comment by cutethotw** [comment]
4.添加uid查询机器人入口——https://t.me/userinfobot

**Comment by AirportR** [comment]
不错的建议，将在后版本中优化。

**Comment by cutethotw** [comment]
第2条是俺没注意config.yaml里的user参数……一开始一并写上的话其实也一样hh

**Comment by cutethotw** [comment]
5.可在config.yaml里进行订阅信息节点的过滤，自动过滤掉名字中有——官网、TG群、用户、流量、天、套餐、Traffic、Expire、挖矿、举报

**Comment by AirportR** [comment]
> 5.可在config.yaml里进行订阅信息节点的过滤的设置，自动过滤掉名字中有——官网、TG群、用户、流量、天、套餐、Traffic、Expire、挖矿、举报——之类的无关节点，甚至可以更近一步实现用户可以自定义正则过滤节点的功能，加油！

优化建议内容已全部实现，此issue将关闭。
