### ISSUE TITLE
动态编译求助

### ISSUE THREAD

**Issue by Noa886** [AirportR/FullTclash#102]
go mod init   应该在哪里目录下初始化
go mod tidy  应该在哪个目录下执行

GOOS=linux GOARCH=arm64 GOARM=7 CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ AR=aarch64-linux-gnu-ar go build -buildmode=c-shared -o fulltclash.so fulltclash.go     应该在哪个目录下执行

没用过这个琢磨了很久了 只能厚脸皮来问了~

![image](https://github.com/AirportR/FullTclash/assets/99782621/75c9e353-d42b-4ac1-90e4-8b29f227a1eb)
我的系统是 AMD构架的 不知道为什么提示这个  不清楚什么问题。

**Comment by GenshinMinecraft** [comment]
回复一下
具体命令大概就这样

mkdir build
cp <FTC路径>/libs/fulltclash.so <FTC路径>/libs/rootCA.crt build/
cd build
go mod init
go mod tidy
GOOS=linux GOARCH=arm64 GOARM=7 CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ AR=aarch64-linux-gnu-ar go build -buildmode=c-shared -o fulltclash.so fulltclash.go

然后再把编译出来的fulltclash.so与fulltclash.h覆盖到<FTC路径>/libs下
完成

**Comment by GenshinMinecraft** [comment]
init与tidy还有编译 都是在复制出来的 fulltclash.go与rootCA.crt 文件夹内执行
编译完将结果放回去即可

**Comment by GenshinMinecraft** [comment]
哦注意一下，你使用的编译命令是arm64架构的，非AMD
如果要编译amd架构的话
直接在本机执行 go build -buildmode=c-shared -o fulltclash.so fulltclash.go 即可

**Comment by Noa886** [comment]
> 哦注意一下，你使用的编译命令是arm64架构的，非AMD 如果要编译amd架构的话 直接在本机执行 go build -buildmode=c-shared -o fulltclash.so fulltclash.go 即可

 蟹蟹。 💕

**Comment by Noa886** [comment]
> 回复一下 具体命令大概就这样
> 
> mkdir build cp <FTC路径>/libs/fulltclash.so <FTC路径>/libs/rootCA.crt build/ cd build go mod init go mod tidy GOOS=linux GOARCH=arm64 GOARM=7 CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ AR=aarch64-linux-gnu-ar go build -buildmode=c-shared -o fulltclash.so fulltclash.go
> 
> 然后再把编译出来的fulltclash.so与fulltclash.h覆盖到<FTC路径>/libs下 完成

cp 了  so 和 crt证书 2个文件  init不需要 .go 文件吗？ 
根据这个步骤生成
![image](https://github.com/AirportR/FullTclash/assets/99782621/9a12df4f-b90c-489d-ba92-68f41cec55d0)

提示缺少go文件包， 是不是复制错了 应该是go 而不是so？

**Comment by AirportR** [comment]
注意，此方法在3.5.9已不适用，请阅读最新的README.md为准。
