### ISSUE TITLE
回显数据图片

### ISSUE THREAD

**Issue by wuyafeiya** [AirportR/FullTclash#105]
纯小白  问一个问题 测试完之后 回显tg的时候 发送文件一直超时 之前是正常的 升级最新版之后 就不行了 

不需要解决 就是不太理解 项目文件看了一遍 没找到向tg机器人发文件的处理 

方便的话可以给点提示 我可以自己去看的 

麻烦了 

项目  真的很好用！

**Comment by AirportR** [comment]
> 

请问你用的是 local 测试还是加了后端呢，还有也可能代理速度不好，更换尝试下。
另外，本地模式（默认模式）的回显代码跟后端模式是不同的，所以你可以先提供多些信息吗。

**Comment by wuyafeiya** [comment]
FullTclash : 3.5.9

环境: Python 3.11.4

系统：win10

代理 : clash 

config.yaml

![截屏2023-07-02 14 48 54](https://github.com/AirportR/FullTclash/assets/49944076/da6df765-5ee8-455b-928b-9000b4d77e19)

local 测试 没有加后端 用的默认的 

测试完成 过一会就会显示这个 

![截屏2023-07-02 14 49 52](https://github.com/AirportR/FullTclash/assets/49944076/b262eb1d-d43c-44d7-99ca-57fcc14206f7)

代理也切换好多了  如果上面都没问题的话 那应该就是我代理网络问题了

**Comment by AirportR** [comment]
我会持续跟进情况，此issue将保持开启，直到问题解决完毕，目前你可以尝试做如下操作:

1. 切换代理
2. 启用clash 代理客户端的TUN模式，进行测试。(注意此模式会导致入门检测失效)
3. 重新搭建
4. 更换机器

从上往下做，应该是可以解决大部分问题，剩下的由我来调查问题，感谢你的支持。❤️

**Comment by wuyafeiya** [comment]
感谢回复 按照上面的步骤 操作 经过排查 是我的机器和网络问题导致的 谢谢 问题已解决
