### ISSUE TITLE
建议单节点测试跳过排序选择

### ISSUE THREAD

**Issue by TCSlX** [AirportR/FullTclash#107]
即在用户仅测试单节点时，跳过排序选择模块。

**Comment by AirportR** [comment]
想要做到这一点，首先得先提取订阅链接里面的节点，这个可能做成回调的方式会比较好。

**Comment by cachexy123** [comment]
> 即在用户仅测试单节点时，跳过排序选择模块。

你好, 我想请问一下, 怎么进行单节点测速的
