### ISSUE TITLE
软件适配非bot版

### ISSUE THREAD

**Issue by C63H88CoN14O14P** [AirportR/FullTclash#110]
作者您好,之前也向您提问过telegram api申请不到的问题,目前我还没有申请到😒
所以还是希望您可以考虑兼容下非bot模式
幸苦您了

**Comment by AirportR** [comment]
> 作者您好,之前也向您提问过telegram api申请不到的问题,目前我还没有申请到😒
> 所以还是希望您可以考虑兼容下非bot模式
> 幸苦您了

事实上，查阅 ./utils/backend.py 就可以看到有一个不需要bot的命令行，但是我好久没维护了，如果你有python功底的话，改改就能用了。另外申请不到api，尝试更换原生节点。

还有，非bot模式的测速方法，有其他更成熟的项目，比如你可以去搜索stair speedtest

**Comment by C63H88CoN14O14P** [comment]
> > 作者您好,之前也向您提问过telegram api申请不到的问题,目前我还没有申请到😒
> > 所以还是希望您可以考虑兼容下非bot模式
> > 幸苦您了
> 
> 事实上，查阅 ./utils/backend.py 就可以看到有一个不需要bot的命令行，但是我好久没维护了，如果你有python功底的话，改改就能用了。另外申请不到api，尝试更换原生节点。
> 
> 还有，非bot模式的测速方法，有其他更成熟的项目，比如你可以去搜索stair speedtest

行吧，python功底是三脚猫的
主要是您的项目比较全面，支持协议也比较多
像stairspeedtest和-reborn都太远古了，而且对于进口ip和出口ip都无法有效检测
不过我倒是发现了个SSRspeedN，除了它的requirements比较难装，别的都还好
谢谢作者回复啦，打扰了
