### ISSUE TITLE
启动后出现错误

### ISSUE THREAD

**Issue by osburt1995** [AirportR/FullTclash#111]
作者您好 请问 启动后出现这个错误是什么原因呢  
PermissionError: [Errno 13] Permission denied: './bin/fulltclash-linux-amd64'

**Comment by AirportR** [comment]
> 作者您好 请问 启动后出现这个错误是什么原因呢  
> PermissionError: [Errno 13] Permission denied: './bin/fulltclash-linux-amd64'  

使用root用户授予上面文件的执行权限
