### ISSUE TITLE
呜呜呜, 大佬们什么时候能测vless

### ISSUE THREAD

**Issue by cachexy123** [AirportR/FullTclash#116]
我的大部分都是vless, 每次测都少好多诶

**Comment by AirportR** [comment]
dev分支已经支持vless,但是我还没合并但主分支

**Comment by cachexy123** [comment]
> dev分支已经支持vless,但是我还没合并但主分支

忘记关了, 其实我昨晚看到了,
对了, 想问问后面能支持单个节点测速吗?

**Comment by cachexy123** [comment]
> dev分支已经支持vless,但是我还没合并但主分支

你好, 我想请问一下, 已经在config.yaml配置了subconvertor, 但实际未生效, 用的是dev分支, 向机器人发送/speedurl, 看到后台输出:subconverter状态: 未启用

**Comment by AirportR** [comment]
试试把subconvertor改成subconverter?
