### ISSUE TITLE
请问启动时提示Unable to connect due to network issues: Connection timed out是为什么？

### ISSUE THREAD

**Issue by soilniba** [AirportR/FullTclash#118]
![image](https://github.com/AirportR/FullTclash/assets/22488208/d387fed0-7125-4d5a-afcc-537dcabd9b5b)
如图，启动时出现一个botmodule.init_bot:<module>:104 - 'NoneType' object has no attribute 'split'的错误，
然后一直提示Unable to connect due to network issues: Connection timed out
命令行是以管理员权限运行的

![image](https://github.com/AirportR/FullTclash/assets/22488208/9fec2ab0-bfef-499a-abc7-bd2f63b6388f)
我的配置信息是这样的，其中proxy是我本地Clash的代理端口

![image](https://github.com/AirportR/FullTclash/assets/22488208/06785cdd-9946-4c17-850d-824840ac6362)
代理端口在telegram中测试有效。

**Comment by AirportR** [comment]
bot:
  proxy:

**Comment by AirportR** [comment]
bot这一级下面还有一个代理，我在README讲过这个
