### ISSUE TITLE
结果中，地区、组织线路不显示

### ISSUE THREAD

**Issue by ogr1432** [AirportR/FullTclash#119]
如下图，机器人配置好跑起来了，但是拓扑图结果中，所属地区，出口所属组织(线路)都没有显示出来，我需要排查哪里，提前感谢热心大佬回复！
![image](https://github.com/AirportR/FullTclash/assets/6716791/cb4b0628-5364-4951-b011-df3dc08000d2)

**Comment by ogr1432** [comment]
admin:
- 50761****
bot:
  api_hash: dc836e**************34f5d4db
  api_id: 26*****591
  bot_token: 6663718808:*****************dq8QjmqNeGLK5Xk
dasn: GeoLite2-ASN.mmdb
dcity: GeoLite2-City.mmdb
dorg: GeoLite2-ASN.mmdb

**Comment by AirportR** [comment]
你先不要使用本地的geo数据库，看看是否正常
