### ISSUE TITLE
analyze测得了入口 测不了出口（显示为0）

### ISSUE THREAD

**Issue by ZiChuanShanFeng** [AirportR/FullTclash#141]
显示为 2023-12-09 14:40:32.015 | INFO     | utils.collector:fetch:185 - Cannot write to closing transport
![Snipaste_2023-12-09_15-01-08](https://github.com/AirportR/FullTclash/assets/139305401/31dfd71d-ef5c-4653-a17c-87ea5707aeb1)

![Topo2023-12-09T14-40-32](https://github.com/AirportR/FullTclash/assets/139305401/cee1500e-0dc1-45a4-bd01-7d1e873025c5)

用的meta内核

**Comment by AirportR** [comment]
自己编译试试吧，再不行就换系统
