### ISSUE TITLE
docker部署重启后报错Unlinking stale socket /tmp/supervisor.sock

### ISSUE THREAD

**Issue by how1ewu** [AirportR/FullTclash#167]

**Comment by aipeach** [comment]
用的是哪个镜像，重启是指重启什么，你启动命令和重启命令是什么呢

**Comment by AirportR** [comment]
> 

麻烦提供一下报错的日志信息

**Comment by how1ewu** [comment]
> 用的是哪个镜像，重启是指重启什么，你启动命令和重启命令是什么呢

使用gui运行会提示参数错误
![](https://s2.loli.net/2024/02/24/Ib7NnR52tpCgBze.png)

**Comment by how1ewu** [comment]
> 麻烦提供一下报错的日志信息

root@howienas:~# docker logs fulltclash 
Unlinking stale socket /tmp/supervisor.sock
root@howienas:~#

**Comment by how1ewu** [comment]
只映射了/app/resources/config.yaml目录到本地，其他没有处理，网络尝试过host和桥接

**Comment by aipeach** [comment]
> > 用的是哪个镜像，重启是指重启什么，你启动命令和重启命令是什么呢
> 
> 使用ghcr.io/airportr/fulltclash:dev镜像，unraid重启，会日志提示：
> 
> ```shell
> root@howienas:~# docker logs fulltclash 
> Unlinking stale socket /tmp/supervisor.sock
> root@howienas:~# 
> ```
用这个镜像看看，`airportr/fulltclash:latest`

**Comment by how1ewu** [comment]
> > > 用的是哪个镜像，重启是指重启什么，你启动命令和重启命令是什么呢
> > 
> > 
> > 使用ghcr.io/airportr/fulltclash:dev镜像，unraid重启，会日志提示：
> > ```shell
> > root@howienas:~# docker logs fulltclash 
> > Unlinking stale socket /tmp/supervisor.sock
> > root@howienas:~# 
> > ```
> 
> 用这个镜像看看，`airportr/fulltclash:latest`

这个目前没有出现问题，我先关闭issus观察一段时间
