### ISSUE TITLE
/register & /baipiao v2board的注册建议

### ISSUE THREAD

**Issue by LittleXingzzZ** [AirportR/fulltclash#190]
1. 希望能自定义注册的账号和密码
2. 或者返回账号和密码以便自己登录进行购买订阅

（因为很多免费机场需要手动订阅免费套餐或者使用优惠券购买免费订阅）

**Comment by AirportR** [comment]
此功能未来可能会废除，因为一个测试订阅的机器人有一个这样的功能会有点诡异
