### ISSUE TITLE
控制台测试功能完善

### ISSUE THREAD

**Issue by RogerProSelf** [AirportR/fulltclash#191]
本机个人自测的情况下部署TG机器人和配套的代理有点繁琐和没必要，希望能完善一下控制台测试的功能，直接用python完成流媒体解锁等测试。

感谢！

**Comment by AirportR** [comment]
繁琐是相对于bot所有者而言的，本项目开发的侧重点就是与telegram bot的操作性。如果有更多人使用同一个bot进行测试，那么它的优势就体现出来了。单纯的命令行测试有其他的项目能够胜任，并且做得更好。

我给你举个例子吧，知道clash吧，clash内核通常需要一个配置文件才能正常的进行工作。对于大多数间接使用clash的而言，他们接触clash最多的可能也就是GUI客户端, 以及从机场这些地方拿到的对应clash配置文件(它是基于yaml格式的)，他们自己往往不需要手搓这些配置文件，就可以一键导入马上享受科学上网的乐趣。这种"便利性"是clash内核本身带来的吗，我想不太见得吧，最初手搓这些clash配置的人,他们才是真正接触，理解clash内核的人，谁又为这些人的"便利性"提供优化？这就回到项目开发组本身了。

说回这个项目，我不会提供在控制台命令行测试的更多便利性，因为这个项目的便利性是利好于bot的用户群体，而非它的搭建者。
如果你想一劳永逸地不使用bot就能无成本地享受这个项目的一切特性，那可能要让你失望了。我尊重每个人的选择，每个同类型的项目都有着自己的特色，选择自己的才是最好的。
