### ISSUE TITLE
自定义speed颜色配置和自定义delay颜色配置未生效

### ISSUE THREAD

**Issue by Miku2563** [AirportR/fulltclash#199]
![ping](https://github.com/user-attachments/assets/aa7acb7d-11a8-4e6c-a43c-2f63ad45c189)
windows10专业。   3.6.13,
编辑config.yaml,所有value值改成#23de36，大小写都试过
![7D3CQ3_M7%)81%8K3SEZ)GJ](https://github.com/user-attachments/assets/050490d2-e8b1-4c82-9001-a17ac45a56e3)
未保存前
![未保存前的](https://github.com/user-attachments/assets/60b15cad-1a28-44ac-9de8-c90143c15c66)
保存测速后
![保存后改变](https://github.com/user-attachments/assets/e2bc44b8-c775-40b8-8e92-7d838171a9e0)
![sudu](https://github.com/user-attachments/assets/c2550bb0-45eb-452d-b33f-f8e5f3c7e9cb)
试过编辑color.yaml,也没生效

**Comment by Miku2563** [comment]
完整config.yaml   admin:
- 56xxxxxxxx
bot:
  api_hash: fb8ae7
  api_id: 2
  bot_token: bGvACU
  proxy: 127.0.0.1:10808
clash:
  path: ./bin/FullTCore
color:
  delay:
  - alpha: 255
    end_color: '#B4C3D0'
    label: 0
    name: "\u4E91\u6C34"
    value: '#23DE36'
  - alpha: 255
    end_color: '#B4C3D0'
    label: 1
    name: "\u4E91\u6C34"
    value: '#23DE36'
  - alpha: 255
    end_color: '#91AEC4'
    label: 100
    name: "\u6674\u5C71"
    value: '#23DE36'
  - alpha: 255
    end_color: '#8BB8CB'
    label: 200
    name: "\u79CB\u6CE2"
    value: '#23DE36'
  - alpha: 255
    end_color: '#5796B3'
    label: 300
    name: "\u5929\u97F5"
    value: '#23DE36'
  - alpha: 255
    end_color: '#1988AE'
    label: 500
    name: "\u9E22\u5C3E"
    value: '#23DE36'
  - alpha: 255
    end_color: '#238BBC'
    label: 1000
    name: "\u7538\u5B50"
    value: '#23DE36'
  - alpha: 255
    end_color: '#2A73AC'
    label: 2000
    name: "\u666F\u6CF0"
    value: '#23DE36'
  - alpha: 255
    label: 99999
    name: "\u666F\u6CF0"
    value: '#23DE36'
  out_color:
  - alpha: 255
    end_color: '#B4C3D0'
    name: "\u4E91\u6C34"
    value: '#23DE36'
  - alpha: 255
    end_color: '#91AEC4'
    name: "\u6674\u5C71"
    value: '#23DE36'
  - alpha: 255
    end_color: '#8BB8CB'
    name: "\u79CB\u6CE2"
    value: '#23DE36'
  - alpha: 255
    end_color: '#5796B3'
    name: "\u5929\u97F5"
    value: '#23DE36'
  - alpha: 255
    end_color: '#1988AE'
    name: "\u9E22\u5C3E"
    value: '#23DE36'
  - alpha: 255
    end_color: '#238BBC'
    name: "\u7538\u5B50"
    value: '#23DE36'
  - alpha: 255
    end_color: '#2A73AC'
    name: "\u666F\u6CF0"
    value: '#23DE36'
  speed:
  - alpha: 255
    end_color: '#B4C3D0'
    label: 0
    name: "\u4E91\u6C34"
    value: '#23DE36'
  - alpha: 255
    end_color: '#91AEC4'
    label: 1
    name: "\u6674\u5C71"
    value: '#23DE36'
  - alpha: 255
    end_color: '#8BB8CB'
    label: 5
    name: "\u79CB\u6CE2"
    value: '#23DE36'
  - alpha: 255
    end_color: '#5796B3'
    label: 10
    name: "\u5929\u97F5"
    value: '#23DE36'
  - alpha: 255
    end_color: '#1988AE'
    label: 20
    name: "\u9E22\u5C3E"
    value: '#23DE36'
  - alpha: 255
    end_color: '#238BBC'
    label: 60
    name: "\u7538\u5B50"
    value: '#23DE36'
  - alpha: 255
    end_color: '#2A73AC'
    label: 100
    name: "\u666F\u6CF0"
    value: '#23DE36'
core: 1
pingurl: https://www.google.com
speedconfig:
  interval: 15
speedfile:
- https://dl.google.com/dl/android/studio/install/2024.2.1.9/android-studio-2024.2.1.9-windows.exe
speedthread: 1
subconverter:
  enable: true
  host: 127.0.0.1:10808
  remoteconfig: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online.ini
user:
- 56xxxxxxx
userconfig:
  usage-ranking:
    560xxxxxxx:
      local: 10

**Comment by Miku2563** [comment]
不知道哪里出了问题

**Comment by AirportR** [comment]
image:
 color:
  speed: 


image是顶层配置，你没写

**Comment by Miku2563** [comment]
原来如此,我眼瞎了，，，，，

**Comment by Miku2563** [comment]
test_download.py里   self.assertTrue(self.loop.run_until_complete(self.dl.dowload()))    最后的dowload是不是少打了一个n, 
                        download
![XF668_0S4SB QWJ0SFX27Q4](https://github.com/user-attachments/assets/4155f4f8-5f3a-49f7-baed-4229c380bbff)

**Comment by Miku2563** [comment]
> test_download.py里 self.assertTrue(self.loop.run_until_complete(self.dl.dowload())) 最后的dowload是不是少打了一个n, download ![XF668_0S4SB QWJ0SFX27Q4](https://private-user-images.githubusercontent.com/92353453/381173839-4155f4f8-5f3a-49f7-baed-4229c380bbff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNTg1ODgsIm5iZiI6MTczMDI1ODI4OCwicGF0aCI6Ii85MjM1MzQ1My8zODExNzM4MzktNDE1NWY0ZjgtNWYzYS00OWY3LWJhZWQtNDIyOWMzODBiYmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDAzMTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmZjgyYTE4NzI4MGU5YWFmODEwZmRmMTc4NWEyYWM1ZTdhODc3ZTllYmMxZTAzODUwYTQ2NTZkYTliN2ZiMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.R533Wu1XpGrIDCCL_msmfg5z_f_Pu1op75AA0OOUon4)

@AirportR
