### ISSUE TITLE
clash cannot dynamically load executable

### ISSUE THREAD

**Issue by Matcha-sama** [AirportR/FullTclash#70]
`OSError: ./resources/clash-linux-amd64: cannot dynamically load executable`
升级3.5.6后出现

**Comment by Matcha-sama** [comment]
3.5.3正常

**Comment by AirportR** [comment]
> 3.5.3正常

新版请删除配置里的
clash:
 path: 
或者重新指向一个正确的动态链接库。

以及需要在bot里输入指令:
/clash start
