### ISSUE TITLE
获取订阅失败

### ISSUE THREAD

**Issue by tangseng110** [AirportR/FullTclash#75]
请问下有知道获取订阅失败原因的朋友吗？
我服务器是国外的服务器，没有设置代理，测试命令：/testurl https://www.bbqq.com/api/v1/client/subscribe?token=12345678
客户端的错误提示如下：
botmodule.command.test:process:139 - 获取         订阅失败!

**Comment by AirportR** [comment]
> 请问下有知道获取订阅失败原因的朋友吗？ 我服务器是国外的服务器，没有设置代理，测试命令：/testurl https://www.bbqq.com/api/v1/client/subscribe?token=12345678 客户端的错误提示如下： botmodule.command.test:process:139 - 获取 订阅失败!

你可以试试，访问你所说的这个域名。还有你可以多拿几个订阅进行测试，看看是否是共同出现问题。

**Comment by tangseng110** [comment]
换了一个订阅确实可以测，看来是我这个机场的问题，但是订阅地址可以正常使用，找不出是哪的问题，待会换个域名试一下，十分感谢楼主的回复
