### ISSUE TITLE
测拓扑报错，其他都正常

### ISSUE THREAD

**Issue by Heartcoolman** [AirportR/FullTclash#97]
2023-06-05 01:26:42.881 | ERROR    | botmodule.command.test:select_export:110 - An error has been caught in function 'select_export', process 'MainProcess' (302723), thread 'MainThread' (139998002622912):
Traceback (most recent call last):

  File "/home/FullTclash/main.py", line 24, in <module>
    start()
    └ <function start at 0x7f53d2fe7d90>

  File "/home/FullTclash/main.py", line 17, in start
    idle()
    └ <function idle at 0x7f53d0f695a0>

  File "/usr/local/lib/python3.10/dist-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
           │    │                  └ <coroutine object idle at 0x7f53a03ffd80>
           │    └ <function BaseEventLoop.run_until_complete at 0x7f53d24a0940>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f53d24a08b0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f53d24a23b0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f53d25f5e10>
    └ <Handle <TaskStepMethWrapper object at 0x7f53a02ca440>()>
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f53a02ca440>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f53a02ca440>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f53a02ca440>()>
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
          │       │        │    │        └ (pyrogram.types.CallbackQuery(id='5196293553608318167', from_user=pyrogram.types.User(id=1209856372, is_self=False, is_contac...
          │       │        │    └ <pyrogram.client.Client object at 0x7f53a068d990>
          │       │        └ <pyrogram.dispatcher.Dispatcher object at 0x7f53a04d76a0>
          │       └ <function callback_loader.<locals>.settings_test at 0x7f53a043b010>
          └ <pyrogram.handlers.callback_query_handler.CallbackQueryHandler object at 0x7f53a043f850>

  File "/home/FullTclash/utils/bot.py", line 297, in settings_test
    await botmodule.select_slave(client, callback_query)
          │         │            │       └ pyrogram.types.CallbackQuery(id='5196293553608318167', from_user=pyrogram.types.User(id=1209856372, is_self=False, is_contact...
          │         │            └ <pyrogram.client.Client object at 0x7f53a068d990>
          │         └ <function select_slave at 0x7f53a04f5ab0>
          └ <module 'botmodule' from '/home/FullTclash/botmodule/__init__.py'>

  File "/home/FullTclash/botmodule/command/setting.py", line 410, in select_slave
    await bot_put(app, originmsg, put_type, None, sort=sort_str, coreindex=2, slaveid=slaveid)
          │       │    │          │                    │                              └ 'local'
          │       │    │          │                    └ '订阅原序'
          │       │    │          └ 'analyze'
          │       │    └ pyrogram.types.Message(id=1038, from_user=pyrogram.types.User(id=1209856372, is_self=False, is_contact=False, is_mutual_conta...
          │       └ <pyrogram.client.Client object at 0x7f53a068d990>
          └ <function bot_put at 0x7f53a04f67a0>

  File "/home/FullTclash/utils/myqueue.py", line 65, in bot_put
    await bot_task_queue(client, message, put_type, q, test_items=test_items, **kwargs)
          │              │       │        │         │             │             └ {'sort': '订阅原序', 'coreindex': 2, 'slaveid': 'local'}
          │              │       │        │         │             └ []
          │              │       │        │         └ <Queue at 0x7f53ced82320 maxsize=1 _queue=[pyrogram.types.Message(id=1038, from_user=pyrogram.types.User(id=1209856372, is_se...
          │              │       │        └ 'analyze'
          │              │       └ pyrogram.types.Message(id=1038, from_user=pyrogram.types.User(id=1209856372, is_self=False, is_contact=False, is_mutual_conta...
          │              └ <pyrogram.client.Client object at 0x7f53a068d990>
          └ <function bot_task_queue at 0x7f53a04f68c0>

  File "/home/FullTclash/utils/myqueue.py", line 28, in bot_task_queue
    await botmodule.process(client, message, put_type=task_type, **kwargs)
          │         │       │       │                 │            └ {'test_items': [], 'sort': '订阅原序', 'coreindex': 2, 'slaveid': 'local'}
          │         │       │       │                 └ 'analyze'
          │         │       │       └ pyrogram.types.Message(id=1038, from_user=pyrogram.types.User(id=1209856372, is_self=False, is_contact=False, is_mutual_conta...
          │         │       └ <pyrogram.client.Client object at 0x7f53a068d990>
          │         └ <function process at 0x7f53ced89000>
          └ <module 'botmodule' from '/home/FullTclash/botmodule/__init__.py'>

  File "/home/FullTclash/botmodule/command/test.py", line 208, in process
    await select_export(message, back_message, put_type, info, **kwargs)
          │             │        │             │         │       └ {'test_items': [], 'sort': '订阅原序', 'coreindex': 2, 'slaveid': 'local'}
          │             │        │             │         └ {'inbound': {'地区': ['CN'], 'AS编号': ['AS58542'], '组织': ['Tianjij,300000'], '栈': ['4'], '簇': [1], '出口数量': [89]}, 'outbound': {'...
          │             │        │             └ 'analyze'
          │             │        └ pyrogram.types.Message(id=1041, date=datetime.datetime(2023, 6, 5, 1, 26, 39), chat=pyrogram.types.Chat(id=1209856372, type=p...
          │             └ pyrogram.types.Message(id=1038, from_user=pyrogram.types.User(id=1209856372, is_self=False, is_contact=False, is_mutual_conta...
          └ <function select_export at 0x7f53ced88ca0>

> File "/home/FullTclash/botmodule/command/test.py", line 110, in select_export
    _, __, image_width2 = export.ExportTopo().exportTopoOutbound(nodename=None,
                          │      └ <class 'utils.export.ExportTopo'>
                          └ <module 'utils.export' from '/home/FullTclash/utils/export.py'>

  File "/home/FullTclash/utils/export.py", line 1288, in exportTopoOutbound
    new_zz = [zz[0]]  # 新的组织列表
              └ []

IndexError: list index out of range
2023-06-05 01:26:42.889 | ERROR    | botmodule.command.test:select_export:140 - cannot unpack non-iterable NoneType object

tg就卡在🍀后端:Local
⏳节点拓扑分析测试进行中...

[====================]

当前进度:
100.00%     [89/89]

**Comment by Heartcoolman** [comment]
仅作入口ip测速的时候是正常的，可以正常出图，仅作出口ip就一样的报错

**Comment by AirportR** [comment]
你是对的，拓扑测试的确会在部分情况下出错，将尽快修复。

**Comment by Heartcoolman** [comment]
> 你是对的，拓扑测试的确会在部分情况下出错，将尽快修复。

大概测试了以下，使用本地ip数据库时，测试出口拓扑出错，不使用时正常
