### ISSUE TITLE
无法申请telegram的api

### ISSUE THREAD

**Issue by C63H88CoN14O14P** [AirportR/FullTclash#99]
这当然不是作者的问题,也与这个程序无关
但是我还是想请问下作者或者其他可以申请到api的是如何操作的
比如,你们的telegram注册用的手机号码
你们使用的网络环境
你们使用的浏览器
打扰了,感谢回复

**Comment by AirportR** [comment]
> 这当然不是作者的问题,也与这个程序无关
> 但是我还是想请问下作者或者其他可以申请到api的是如何操作的
> 比如,你们的telegram注册用的手机号码
> 你们使用的网络环境
> 你们使用的浏览器
> 打扰了,感谢回复

历经半年的测试，无法申请api大部分情况下都是节点的问题。

根据你所描述的，申请api的一些技巧:

1. 手机号码最好不是虚拟号，如果gv
2. 节点要求干净，最好是家宽。尽量和号码地区对应上。
3. 浏览器开启无痕模式去申请。
4. 如果一个节点申请不成功，更换节点后，重复以上步骤。
5. 目测地区家宽成功概率高点

**Comment by C63H88CoN14O14P** [comment]
> > 这当然不是作者的问题,也与这个程序无关
> > 但是我还是想请问下作者或者其他可以申请到api的是如何操作的
> > 比如,你们的telegram注册用的手机号码
> > 你们使用的网络环境
> > 你们使用的浏览器
> > 打扰了,感谢回复
> 
> 历经半年的测试，无法申请api大部分情况下都是节点的问题。
> 
> 根据你所描述的，申请api的一些技巧:
> 
> 1. 手机号码最好不是虚拟号，比如gv
> 2. 节点要求干净，最好是家宽。尽量和号码地区对应上。
> 3. 浏览器开启无痕模式去申请。
> 4. 如果一个节点申请不成功，更换节点后，重复以上步骤。
> 5. 目测地区家宽成功概率高点

我真的是个非酋，我昨天拿了个土耳其的电话，用土耳其节点也是error，真的是醉了
 作者能后考虑做一个无须telegram api的纯本地运行版的测速软件？感激不尽😊

**Comment by AirportR** [comment]
也会以后会，但我侧重于tg bot
